language: cpp
compiler: 
  - gcc
  - clang
before_install:
  - sudo apt-get install -y php7.0-dev unzip
  - wget https://github.com/CopernicaMarketingSoftware/PHP-CPP/archive/v2.1.4.zip
  - unzip v2.1.4.zip
  - cd PHP-CPP-2.1.4/ && make && sudo make install
script: make
